qlns/routes/web.php
<?php

Route::get('/', function () {
    return view('login');
});

Route::resource('phong', 'PhongController')->middleware('admin');
Route::resource('nhanvien', 'NhanVienController');

Route::get('login', 'LoginController@getLogin')->name('login');
Route::post('login', 'LoginController@postLogin');
Route::get('logout', 'LogoutController@getLogout');

qlns/resources/views/deleteModal.blade.php
<div id="confirmModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" id="add_close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Xác nhận</h2>
            </div>
            <div class="modal-body">
                <span id="form_result"></span>
                <h4 align="center" style="margin:0;">Bạn chắc chắn muốn xóa chứ?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">Đồng ý</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
            </div>
        </div>
    </div>
</div>

qlns/resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Đăng nhập</title>
    <!-- Latest compiled and minified CSS & JS -->
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
        integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="//code.jquery.com/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
        integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous">
    </script>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <form action="#" method="POST" role="form">
                    <legend>Đăng nhập</legend>

                    <div class="alert alert-danger error errorLogin" style="display: none;">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <p style="color:red; display:none;" class="error errorLogin"></p>
                    </div>

                    <div class="form-group">
                        <label for="">Email</label>
                        <input type="text" class="form-control" id="email" placeholder="Email" name="email"
                            value="{{old('email')}}">
                        <p style="color:red; display: none" class="error errorEmail"></p>
                    </div>
                    <div class="form-group">
                        <label for="">Mật khẩu</label>
                        <input type="password" class="form-control" id="password" placeholder="Password"
                            name="password">
                        <p style="color:red; display: none" class="error errorPassword"></p>
                    </div>
                    <div class="form-group">
                        <input type="checkbox" name="remember"> Ghi nhớ
                    </div>


                    <button id="dang-nhap" type="submit" class="btn btn-primary">Đăng nhập</button>
                </form>
            </div>
        </div>
    </div>
</body>
<script src="{{url('js/login.js')}}"></script>

</html>

qlns/resources/views/nhanVienModal.blade.php
<div id="AddModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" id="add_close" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Thêm mới</h4>
            </div>
            <div class="modal-body">
                <span id="form_result"></span>
                <form method="post" id="sample_form" class="form-horizontal" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label class="control-label col-md-4">Họ Tên : </label>
                        <div class="col-md-8">
                            <input type="text" name="hoTen" id="hoTen" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">Địa Chỉ : </label>
                        <div class="col-md-8">
                            <input type="text" name="diaChi" id="diaChi" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">ID Phòng : </label>
                        <div class="col-md-8">
                            <input type="text" name="id_phong" id="id_phong" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">Số điện Thoại : </label>
                        <div class="col-md-8">
                            <input type="text" name="sdt" id="sdt" class="form-control" />
                        </div>
                    </div>
                    <br />
                    <div class="form-group" align="center">
                        <input type="hidden" name="action" id="action" />
                        <input type="hidden" name="hidden_id" id="hidden_id" />
                        <input type="submit" name="action_button" id="action_button" class="btn btn-warning"
                            value="Add" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

qlns/resources/views/nhanvien.blade.php
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Quản Lý</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>

<body>
    @if (session('status'))
    <div class="alert-danger" style="text-align: center; font-size: 20px;">
        {{ session('status') }}
    </div>
    @endif
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{route('nhanvien.index')}}">Nhân Viên</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Phòng Ban <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a id="show_id" data-url="{{route('nhanvien.show','1')}}">Kế hoạch</a></li>
                            <li><a id="show_id" data-url="{{route('nhanvien.show','2')}}">Đào tạo</a></li>
                            <li><a id="show_id" data-url="{{route('nhanvien.show','3')}}">Ý tưởng</a></li>
                            <li><a id="show_id" data-url="{{route('nhanvien.show','4')}}">Kinh doanh</a></li>
                            <li style="text-align: center;"><button><a href="http://localhost/phong">Quản
                                        lý</a></button></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{Auth::user()->name}} <b
                                class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{url('logout')}}">Đăng xuất</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div align="right">
            <button type="button" name="create_record" id="create_record" class="btn btn-success btn-sm">Thêm
                mới</button>
        </div>
        <br />
        <div class="table-responsive">
            <table class="table table-bordered table-striped" id="user_table" style="text-align: center;">
                <thead>
                    <tr>
                        <th width="25%" style="text-align: center;">Họ Tên</th>
                        <th width="25%" style="text-align: center;">Địa Chỉ</th>
                        <th width="25%" style="text-align: center;">SĐT</th>
                        <th width="25%" style="text-align: center;">Hành Động</th>
                    </tr>
                </thead>
            </table>
        </div>
        <br />
        <br />
    </div>
</body>
@include ('nhanVienModal')
@include ('deleteModal')
<script src="{{url('js/ql_nhanvien.js')}}"></script>

</html>

qlns/resources/views/phong.blade.php
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Quản Lý</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>

<body>
    <div class="container">
        <br />
        <div align="right">
            <button type="button" name="create_record" id="create_record" class="btn btn-success btn-sm">Thêm
                mới</button>
        </div>
        <br />
        <div class="table-responsive">
            <table class="table table-bordered table-striped" id="user_table" style="text-align: center;">
                <thead>
                    <tr>
                        <th width="15%" style="text-align: center;">ID Phòng</th>
                        <th width="25%" style="text-align: center;">Tên Phòng</th>
                        <th width="35%" style="text-align: center;">Mô Tả </th>
                        <th width="25%" style="text-align: center;">Hành Động</th>
                    </tr>
                </thead>
            </table>
        </div>
        <br />
        <br />
    </div>
</body>
@include ('phongModal')
@include ('deleteModal')
<script src="{{url('js/ql_phong.js')}}"></script>

</html>

qlns/resources/views/phongModal.blade.php
<div id="AddModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" id="add_close" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Thêm mới</h4>
            </div>
            <div class="modal-body">
                <span id="form_result"></span>
                <form method="post" id="sample_form" class="form-horizontal" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label class="control-label col-md-4">Tên Phòng: </label>
                        <div class="col-md-8">
                            <input type="text" name="ten_phong" id="ten_phong" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">Mô Tả: </label>
                        <div class="col-md-8">
                            <input type="text" name="mo_ta" id="mo_ta" class="form-control" />
                        </div>
                    </div>
                    <br />
                    <div class="form-group" align="center">
                        <input type="hidden" name="action" id="action" />
                        <input type="hidden" name="hidden_id" id="hidden_id" />
                        <input type="submit" name="action_button" id="action_button" class="btn btn-warning"
                            value="Add" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>